//! Built-in entries for common commands whose help output is not parseable
//! (no `--help`, prose-style usage, uncolumned option lists).
//!
//! Used only as a fallback when `--help` harvesting yields no entries — the
//! parser stays the primary source. Descriptions are intentionally short.

use crate::suggest::Entry;

/// Curated `(insert, description)` rows for `base`, if we ship any.
pub fn entries(base: &str) -> Option<Vec<Entry>> {
    let rows: &[(&str, &str)] = match base {
        "ssh" => &[
            ("-p", "port to connect to on the remote host"),
            ("-i", "identity (private key) file"),
            ("-l", "login user name"),
            ("-L", "local port forwarding (local:host:remote)"),
            ("-R", "remote port forwarding (remote:host:local)"),
            ("-J", "jump host (ProxyJump)"),
            ("-N", "no remote command (forwarding only)"),
            ("-t", "force pseudo-terminal allocation"),
            ("-X", "enable X11 forwarding"),
            ("-v", "verbose (repeat for more)"),
        ],
        "scp" => &[
            ("-r", "copy directories recursively"),
            ("-P", "port to connect to on the remote host"),
            ("-i", "identity (private key) file"),
            ("-p", "preserve times and modes"),
            ("-C", "enable compression"),
            ("-q", "quiet mode"),
        ],
        "ip" => &[
            ("address", "protocol (IP) addresses on devices"),
            ("link", "network devices"),
            ("route", "routing table entries"),
            ("neigh", "neighbour (ARP/NDISC) tables"),
            ("rule", "routing policy rules"),
            ("netns", "network namespaces"),
            ("tunnel", "IP tunnels"),
            ("monitor", "watch netlink messages"),
            ("-br", "brief output"),
            ("-j", "JSON output"),
        ],
        "ps" => &[
            ("aux", "all processes, BSD format"),
            ("-ef", "all processes, full format"),
            ("-u", "processes of a user"),
            ("-C", "processes by command name"),
            ("--forest", "process tree"),
            ("-o", "custom output format (e.g. pid,cmd,%mem)"),
        ],
        "pacman" => &[
            ("-S", "sync: install packages from repositories"),
            ("-Syu", "sync: refresh databases and upgrade system"),
            ("-Ss", "sync: search repositories"),
            ("-R", "remove packages"),
            ("-Rns", "remove with dependencies and configs"),
            ("-Q", "query installed packages"),
            ("-Qi", "query: package details"),
            ("-U", "upgrade/install from a package file"),
            ("-F", "query the files database"),
        ],
        "openssl" => &[
            ("s_client", "test/debug a TLS connection to a server"),
            ("s_server", "run a simple TLS/SSL test server"),
            ("x509", "inspect, convert, or sign X.509 certificates"),
            ("req", "create/inspect certificate signing requests (CSR)"),
            ("genrsa", "generate an RSA private key"),
            ("genpkey", "generate a private key (any algorithm)"),
            ("rsa", "inspect or convert RSA keys"),
            ("pkey", "inspect or convert private keys (any algorithm)"),
            ("enc", "symmetric encryption/decryption"),
            ("dgst", "message digests and signing (e.g. -sha256)"),
            ("verify", "verify a certificate chain"),
            ("pkcs12", "build or parse PKCS#12 (.p12/.pfx) files"),
            ("rand", "generate random bytes"),
            ("ciphers", "list supported TLS cipher suites"),
        ],
        // --- Security / pentest tools (defensive & educational use) ---
        "nmap" => &[
            ("-sS", "TCP SYN (stealth) scan"),
            ("-sV", "probe open ports to determine service/version"),
            ("-sC", "run default NSE scripts"),
            (
                "-A",
                "aggressive: OS detection, version, scripts, traceroute",
            ),
            ("-O", "enable OS detection"),
            ("-p", "port ranges (e.g. -p 1-1000, -p-)"),
            ("-Pn", "treat all hosts as online (skip host discovery)"),
            ("-sU", "UDP scan"),
            ("-T4", "faster timing template (0 slow … 5 insane)"),
            ("-oN", "normal output to file"),
            ("-oA", "output in all formats (base name)"),
            ("--script", "run NSE scripts (e.g. --script vuln)"),
        ],
        "masscan" => &[
            ("-p", "ports to scan (e.g. -p80,443, -p0-65535)"),
            ("--rate", "packets per second"),
            ("--range", "IP range to scan"),
            ("-oX", "XML output to file"),
            ("--banners", "grab banners from open ports"),
            ("-e", "network interface to use"),
        ],
        "sqlmap" => &[
            ("-u", "target URL"),
            ("-r", "load HTTP request from a file"),
            ("--data", "POST data string"),
            ("--dbs", "enumerate databases"),
            ("--tables", "enumerate tables"),
            ("--dump", "dump table entries"),
            ("--batch", "never ask, use defaults"),
            ("--level", "test level 1-5"),
            ("--risk", "risk of tests 1-3"),
            ("--technique", "SQLi techniques (BEUSTQ)"),
        ],
        "hydra" => &[
            ("-l", "single login name"),
            ("-L", "login name list file"),
            ("-p", "single password"),
            ("-P", "password list file"),
            ("-t", "parallel tasks per target"),
            ("-s", "port"),
            ("-f", "stop after first valid pair"),
            ("-V", "verbose: show every attempt"),
        ],
        "john" => &[
            ("--wordlist", "wordlist mode (file of candidates)"),
            ("--rules", "enable word-mangling rules"),
            ("--format", "hash format (e.g. --format=nt)"),
            ("--incremental", "brute-force (incremental) mode"),
            ("--show", "show cracked passwords"),
            ("--session", "name this session (resumable)"),
            ("--restore", "resume an interrupted session"),
        ],
        "hashcat" => &[
            ("-m", "hash type/mode (e.g. -m 0 MD5, -m 1000 NTLM)"),
            ("-a", "attack mode (0 straight, 3 mask)"),
            ("-o", "output file for cracked hashes"),
            ("--show", "show already-cracked hashes"),
            ("-r", "rules file"),
            ("--force", "ignore warnings"),
            ("-w", "workload profile 1-4"),
        ],
        "gobuster" => &[
            ("dir", "directory/file brute-forcing mode"),
            ("dns", "DNS subdomain brute-forcing mode"),
            ("vhost", "virtual host brute-forcing mode"),
            ("-u", "target URL"),
            ("-w", "wordlist path"),
            ("-x", "file extensions (e.g. -x php,txt)"),
            ("-t", "number of concurrent threads"),
        ],
        "ffuf" => &[
            ("-u", "target URL (use FUZZ keyword)"),
            ("-w", "wordlist path (optionally :KEYWORD)"),
            ("-H", "header (e.g. -H 'Host: FUZZ')"),
            ("-X", "HTTP method"),
            ("-d", "POST data"),
            ("-mc", "match HTTP status codes"),
            ("-fc", "filter out HTTP status codes"),
            ("-fs", "filter out response sizes"),
            ("-recursion", "follow discovered directories"),
        ],
        "feroxbuster" => &[
            ("-u", "target URL"),
            ("-w", "wordlist path"),
            ("-x", "file extensions to search for"),
            ("-t", "number of threads"),
            ("-d", "maximum recursion depth"),
            ("-r", "follow redirects"),
        ],
        "nikto" => &[
            ("-h", "target host or URL"),
            ("-p", "port(s) to scan"),
            ("-ssl", "force SSL"),
            ("-Tuning", "scan tuning (test categories)"),
            ("-o", "output file"),
            ("-Format", "output format (csv, htm, xml)"),
        ],
        "wpscan" => &[
            ("--url", "target WordPress URL"),
            ("--enumerate", "enumerate (u users, p plugins, t themes)"),
            (
                "--plugins-detection",
                "detection mode (passive/mixed/aggressive)",
            ),
            ("--api-token", "WPScan API token for vuln data"),
            ("--passwords", "password list for brute force"),
            ("--usernames", "usernames to try"),
        ],
        "nuclei" => &[
            ("-u", "target URL"),
            ("-l", "file with list of targets"),
            ("-t", "templates or template dir to run"),
            ("-severity", "filter by severity (low..critical)"),
            ("-tags", "run templates matching tags"),
            ("-o", "output file"),
            ("-rl", "rate limit (requests per second)"),
        ],
        "tcpdump" => &[
            ("-i", "interface to capture on (-i any for all)"),
            ("-w", "write raw packets to a .pcap file"),
            ("-r", "read packets from a .pcap file"),
            ("-n", "do not resolve names"),
            ("-c", "stop after N packets"),
            ("-v", "verbose (repeat for more)"),
            ("-A", "print packet payload as ASCII"),
            ("-X", "print payload in hex and ASCII"),
            ("port", "filter: port 80 / host x / src / dst"),
        ],
        "nc" | "ncat" | "netcat" => &[
            ("-l", "listen mode (server)"),
            ("-p", "local port"),
            ("-v", "verbose"),
            ("-n", "no DNS resolution"),
            ("-z", "zero-I/O (port scan)"),
            ("-u", "UDP instead of TCP"),
            ("-w", "connection timeout in seconds"),
            ("-e", "execute program after connect (traditional nc)"),
        ],
        "aircrack-ng" => &[
            ("-w", "wordlist(s) for WPA cracking"),
            ("-b", "target BSSID (AP MAC)"),
            ("-e", "target ESSID (network name)"),
            ("-a", "force attack mode (1 WEP, 2 WPA)"),
        ],
        "find" => &[
            ("-name", "match file name (glob, case sensitive)"),
            ("-iname", "match file name (glob, case insensitive)"),
            ("-type", "match type: f file, d directory, l symlink"),
            ("-size", "match size (e.g. +10M, -1k)"),
            ("-mtime", "match modification time in days"),
            ("-maxdepth", "descend at most N directory levels"),
            ("-path", "match full path (glob)"),
            ("-exec", "run a command on each match ({} \\;)"),
            ("-delete", "delete matched files"),
        ],
        _ => return None,
    };
    Some(
        rows.iter()
            .map(|(insert, desc)| Entry {
                insert: insert.to_string(),
                display: insert.to_string(),
                desc: desc.to_string(),
            })
            .collect(),
    )
}
